[package]
name = "crust-of-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[dev-dependencies]
criterion = "0.3.5"
pretty_assertions = "1.2.1"
test-case = "2.1.0"

[[bench]]
name = "sorting_benchmark"
harness = false
